name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 6
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_traffic: yes
